export const ALL_APPOINTMENT_REQUEST = 'ALL_APPOINTMENT_REQUEST'
export const ALL_APPOINTMENT_SUCCESS = 'ALL_APPOINTMENT_SUCCESS'
export const ALL_APPOINTMENT_FAIL = 'ALL_APPOINTMENT_FAIL'

export const NEW_APPOINTMENT_REQUEST = 'NEW_APPOINTMENT_REQUEST'
export const NEW_APPOINTMENT_SUCCESS = 'NEW_APPOINTMENT_SUCCESS'
export const NEW_APPOINTMENT_FAIL = 'NEW_APPOINTMENT_FAIL'
export const NEW_APPOINTMENT_RESET= 'NEW_APPOINTMENT_RESET'




export const CLEAR_ERRORS = "CLEAR_ERRORS"