export const ALL_APPOINTMENT_REQUEST = 'ALL_APPOINTMENT_REQUEST'
export const ALL_APPOINTMENT_SUCCESS = 'ALL_APPOINTMENT_SUCCESS'
export const ALL_APPOINTMENT_FAIL = 'ALL_APPOINTMENT_FAIL'




export const CLEAR_ERRORS = "CLEAR_ERRORS"