export const ALL_BARBER_REQUEST = 'ALL_BARBER_REQUEST'
export const ALL_BARBER_SUCCESS = 'ALL_BARBER_SUCCESS'
export const ALL_BARBER_FAIL = 'ALL_BARBER_FAIL'


export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const ALL_REVIEW_REQUEST = 'ALL_REVIEW_REQUEST'
export const ALL_REVIEW_SUCCESS = 'ALL_REVIEW_SUCCESS'
export const ALL_REVIEW_FAIL = 'ALL_REVIEW_FAIL'



export const CLEAR_ERRORS = "CLEAR_ERRORS"