export const ALL_BARBER_REQUEST = 'ALL_BARBER_REQUEST'
export const ALL_BARBER_SUCCESS = 'ALL_BARBER_SUCCESS'
export const ALL_BARBER_FAIL = 'ALL_BARBER_FAIL'


export const NEW_BARBER_REQUEST = 'NEW_BARBER_REQUEST'
export const NEW_BARBER_SUCCESS = 'NEW_BARBER_SUCCESS'
export const NEW_BARBER_RESET = 'NEW_BARBER_RESET'
export const NEW_BARBER_FAIL = 'NEW_BARBER_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"