export const ALL_BARBER_DETAILS_REQUEST = 'ALL_BARBER_DETAILS_REQUEST'
export const ALL_BARBER_DETAILS_SUCCESS = 'ALL_BARBER_DETAILS_SUCCESS'
export const ALL_BARBER_DETAILS_FAIL = 'ALL_BARBER_DETAILS_FAIL'


export const ALL_BARBER_URL_REQUEST = 'ALL_BARBER_URL_REQUEST'
export const ALL_BARBER_URL_SUCCESS = 'ALL_BARBER_URL_SUCCESS'
export const ALL_BARBER_URL_FAIL = 'ALL_BARBER_URL_FAIL'




export const CLEAR_ERRORS = "CLEAR_ERRORS"