export const ALL_BARBER_REQUEST = 'ALL_BARBER_REQUEST'
export const ALL_BARBER_SUCCESS = 'ALL_BARBER_SUCCESS'
export const ALL_BARBER_FAIL = 'ALL_BARBER_FAIL'




export const CLEAR_ERRORS = "CLEAR_ERRORS"