export const ALL_REVIEW_REQUEST = 'ALL_REVIEW_REQUEST'
export const ALL_REVIEW_SUCCESS = 'ALL_REVIEW_SUCCESS'
export const ALL_REVIEW_FAIL = 'ALL_REVIEW_FAIL'

export const ALL_REVIEW_AVERAGE_REQUEST = 'ALL_REVIEW_AVERAGE_REQUEST'
export const ALL_REVIEW_AVERAGE_SUCCESS = 'ALL_REVIEW_AVERAGE_SUCCESS'
export const ALL_REVIEW_AVERAGE_FAIL = 'ALL_REVIEW_AVERAGE_FAIL'

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL'
export const CREATE_REVIEW_RESET= 'CREATE_REVIEW_RESET'




export const CLEAR_ERRORS = "CLEAR_ERRORS"