export const ALL_SALON_DETAILS_REQUEST = 'ALL_SALON_DETAILS_REQUEST'
export const ALL_SALON_DETAILS_SUCCESS = 'ALL_SALON_DETAILS_SUCCESS'
export const ALL_SALON_DETAILS_FAIL = 'ALL_SALON_DETAILS_FAIL'

export const ALL_SALON_COORDINATES_REQUEST = 'ALL_SALON_COORDINATES_REQUEST'
export const ALL_SALON_COORDINATES_SUCCESS = 'ALL_SALON_COORDINATES_SUCCESS'
export const ALL_SALON_COORDINATES_FAIL = 'ALL_SALON_COORDINATES_FAIL'



export const CLEAR_ERRORS = "CLEAR_ERRORS"