export const ALL_SALON_REQUEST = 'ALL_SALON_REQUEST'
export const ALL_SALON_SUCCESS = 'ALL_SALON_SUCCESS'
export const ALL_SALON_FAIL = 'ALL_SALON_FAIL'

export const ADMIN_SALON_REQUEST = 'ADMIN_SALON_REQUEST'
export const ADMIN_SALON_SUCCESS = 'ADMIN_SALON_SUCCESS'
export const ADMIN_SALON_FAIL = 'ADMIN_SALON_FAIL'


export const NEW_SALON_REQUEST = 'NEW_SALON_REQUEST'
export const NEW_SALON_SUCCESS = 'NEW_SALON_SUCCESS'
export const NEW_SALON_RESET = 'NEW_SALON_RESET'
export const NEW_SALON_FAIL = 'NEW_SALON_FAIL'



export const CLEAR_ERRORS = "CLEAR_ERRORS"